site_name: 'Minha Documentação'
theme:
  name: 'material'
  palette:
    scheme: 'slate'
extra_css:
  - css/styles.css  
  - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.js
  - js/script.js  

nav:
  - Home: index.md

  # Seção Back-end
  - Back-end:
      - Tela de Teste: tela1.md
      - Tela de Teste2: tela2.md
      - Tela de Teste3: tela3.md
      - Tela de Teste4: tela4.md
      - Tela de Teste5: tela5.md

  # Seção Front-end
  - Front-end:
      - Tela de Login: login.md
      - Tela de Cadastro: novo_cadastro.md
      - Tela Relatorio Financeiro: relatorio.md
      - Tela Gerenciar: gerenciar.md
      - Tela de Planos: planos.md
      - Tela Home Varzeano: varzeano.md
      - Tela Tabela de Preços: tabela_preco.md
      - Tela Criar Time: criar_time.md
      - Tela Criar Clube: criar_clube.md
      - Tela Convidar Varzeano: convidar.md
